apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-28T01:03:47Z"
  generation: 1
  labels:
    app: horsebets
  name: horsebets
  namespace: horsebets
  resourceVersion: "212009403"
  uid: 878e9972-4197-46bf-af82-be644fef818f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horsebets
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: horsebets
    spec:
      containers:
      - image: paulgmiller/horsebets:7468880
        name: horsebets
        resources: {}
        env:
        - name: MSSQL_DSN
          valueFrom:
            secretKeyRef:
              key: MSSQL_DSN
              name: horsebets
