apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: horsebets
  name: horsebets
  namespace: horsebets
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: horsebets
  strategy:
    rollingUpdate:
      maxSurge: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: horsebets
    spec:
      containers:
      - image: paulgmiller/horsebets:790cd19
        name: horsebets
        resources: {}
        env:
        - name: MSSQL_DSN
          valueFrom:
            secretKeyRef:
              key: MSSQL_DSN
              name: horsebets
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
